name: tindatap
description: "A simple, offline POS and Inventory system for sari-sari stores."
publish_to: "none"

version: 1.0.2+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: any
  intl: ^0.18.1
  provider: ^6.1.1
  share_plus: ^7.0.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  file_selector: ^0.9.0
  crypto: ^3.0.3
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/tindatap_icon.png
  remove_alpha_ios: true
